; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "Prime Drive"
#define MyAppVersion "1.5"
#define MyAppPublisher "Prive Drive"
#define MyAppExeName "Trabajo practico IS.exe"
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C92C7135-4B76-410F-8FC4-C20F54C82B48}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\Usuario\Desktop
OutputBaseFilename=Instalador_PrimeDrive_v1
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Usuario\Desktop\Proyecto Diploma\Proyecto-Diploma-PrimeDrive\Trabajo practico IS\Trabajo practico IS\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\Desktop\Proyecto Diploma\Proyecto-Diploma-PrimeDrive\Trabajo practico IS\Trabajo practico IS\bin\Release\BE.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\Desktop\Proyecto Diploma\Proyecto-Diploma-PrimeDrive\Trabajo practico IS\Trabajo practico IS\bin\Release\BLL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\Desktop\Proyecto Diploma\Proyecto-Diploma-PrimeDrive\Trabajo practico IS\Trabajo practico IS\bin\Release\DAL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\Desktop\Proyecto Diploma\Proyecto-Diploma-PrimeDrive\Trabajo practico IS\Trabajo practico IS\bin\Release\Servicios.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\Desktop\Proyecto Diploma\Proyecto-Diploma-PrimeDrive\Trabajo practico IS\Trabajo practico IS\bin\Release\Trabajo practico IS.exe.config"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

